---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: elastic-helm
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/kaushik51094/elastic-helm

