kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticui
  template:
    metadata:
      labels:
        app: elasticui
    spec:
      containers:
        - name: elasticui
          image: kaushik51094/elasticui:v2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: elasticui
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
  selector:
    app: elasticui
